<?php
// Copyright (c) Skin Cancer College Australasia.
// All rights reserved.
//
// This file is part of a proprietary plugin developed by Skin Cancer
// College Australasia for use with Moodle. It is NOT free software and is
// NOT released under the GNU General Public License.
//
// Unauthorised copying, distribution, modification, or use of this file,
// in whole or in part, via any medium, is strictly prohibited without the
// prior written permission of Skin Cancer College Australasia. The software
// is provided "as is", without warranty of any kind, express or implied.

/**
 * Plugin-level callbacks.
 *
 * @package    tool_imageextractor
 * @copyright  © Skin Cancer College Australasia
 * @license    Proprietary — Skin Cancer College Australasia, all rights reserved
 */

/**
 * Serve the ZIP volumes and manifest generated by an extraction job, and the
 * uploaded replacement images used by a replace job (for the review preview).
 *
 * Only holders of tool/imageextractor:manage at the system context can fetch
 * them - the archives can contain any file in the site.
 *
 * @param stdClass $course
 * @param stdClass $cm
 * @param context $context
 * @param string $filearea
 * @param array $args
 * @param bool $forcedownload
 * @param array $options
 * @return bool False if the file cannot be served; otherwise it is sent and the script exits.
 */
function tool_imageextractor_pluginfile($course, $cm, $context, $filearea, $args, $forcedownload, array $options = []): bool {
    unset($course, $cm);

    if ($context->contextlevel !== CONTEXT_SYSTEM) {
        return false;
    }
    if (!in_array($filearea, ['volumes', 'manifest', 'replacement'], true)) {
        return false;
    }

    require_login();
    require_capability('tool/imageextractor:manage', $context);

    $itemid = (int) array_shift($args);
    $filename = array_pop($args);
    $filepath = $args ? '/' . implode('/', $args) . '/' : '/';

    $fs = get_file_storage();
    $file = $fs->get_file($context->id, 'tool_imageextractor', $filearea, $itemid, $filepath, $filename);
    if (!$file || $file->is_directory()) {
        return false;
    }

    // The replacement images are shown inline as thumbnails on the review page
    // and are cacheable; the (potentially very large) archives are always
    // downloaded.
    if ($filearea === 'replacement') {
        send_stored_file($file, DAYSECS, 0, false, $options);
    } else {
        send_stored_file($file, 0, 0, true, $options);
    }
}

/**
 * Render a small progress bar with a "done / total (pct%)" caption, used on
 * the jobs overview and the job view page.
 *
 * @param int $done Items processed so far.
 * @param int $total Total items the job matched.
 * @return string HTML, or an em dash when there is nothing to report.
 */
function tool_imageextractor_progress_bar(int $done, int $total): string {
    if ($total <= 0) {
        return '-';
    }
    $done = min(max($done, 0), $total);
    $pct = (int) round(($done / $total) * 100);

    $bar = html_writer::div(
        html_writer::div('', 'progress-bar', [
            'role' => 'progressbar',
            'style' => 'width: ' . $pct . '%',
            'aria-valuenow' => $pct,
            'aria-valuemin' => 0,
            'aria-valuemax' => 100,
            'aria-label' => get_string('progress', 'tool_imageextractor'),
        ]),
        'progress',
        ['style' => 'min-width: 6em']
    );
    return $bar . html_writer::div($done . ' / ' . $total . ' (' . $pct . '%)', 'small text-nowrap');
}

/**
 * Render the destructive-replace confirmation preview for a job: a side-by-side
 * thumbnail comparison of the first few matched targets with the replacement
 * that will be written, followed by a sample table naming each resolved
 * replacement (or flagging targets with no match). Replacements are resolved
 * through the same path the apply uses, so the preview links the exact file
 * that will be written.
 *
 * @param stdClass $job The replace job (its replacement source is stored).
 * @param moodle_url $viewurl The job view URL (unused placeholder for symmetry).
 * @return void
 */
function tool_imageextractor_render_replace_preview(stdClass $job, moodle_url $viewurl): void {
    global $OUTPUT;
    unset($viewurl);

    $review = \tool_imageextractor\manager::review_summary((int) $job->id);
    echo $OUTPUT->heading(get_string('replacepreviewheading', 'tool_imageextractor'), 3);
    echo html_writer::div(get_string('reviewsummary', 'tool_imageextractor', (object) [
        'total'       => $review['total'],
        'willreplace' => $review['willreplace'],
        'willskip'    => $review['willskip'],
    ]), 'mb-2');

    $replacer = new \tool_imageextractor\replacer($job);
    $thumbrows = array_slice($review['rows'], 0, 5);
    if ($thumbrows) {
        echo $OUTPUT->heading(get_string('previewthumbsheading', 'tool_imageextractor'), 4);
        $ttable = new html_table();
        $ttable->attributes['class'] = 'generaltable';
        $ttable->head = [
            get_string('colcurrentimage', 'tool_imageextractor'),
            get_string('colreplacementimage', 'tool_imageextractor'),
            get_string('colfilename', 'tool_imageextractor'),
        ];
        foreach ($thumbrows as $prow) {
            $oldurl = null;
            if (strpos((string) $prow->mimetype, 'image/') === 0) {
                $oldurl = moodle_url::make_pluginfile_url(
                    $prow->contextid,
                    $prow->component,
                    $prow->filearea,
                    $prow->fileitemid,
                    $prow->filepath,
                    $prow->filename
                );
            }
            $newurl = null;
            $replacementfile = $replacer->replacement_for($prow->filename);
            if ($replacementfile) {
                $newurl = moodle_url::make_pluginfile_url(
                    $replacementfile->get_contextid(),
                    $replacementfile->get_component(),
                    $replacementfile->get_filearea(),
                    $replacementfile->get_itemid(),
                    $replacementfile->get_filepath(),
                    $replacementfile->get_filename()
                );
            }
            $ttable->data[] = [
                tool_imageextractor_thumbnail($oldurl, get_string('colcurrentimage', 'tool_imageextractor')),
                tool_imageextractor_thumbnail($newurl, get_string('colreplacementimage', 'tool_imageextractor')),
                s($prow->filename),
            ];
        }
        echo html_writer::table($ttable);
    }

    if ($review['rows']) {
        $ptable = new html_table();
        $ptable->attributes['class'] = 'generaltable';
        $ptable->head = [
            get_string('colfilename', 'tool_imageextractor'),
            get_string('component', 'tool_imageextractor'),
            get_string('filearea', 'tool_imageextractor'),
            get_string('colsize', 'tool_imageextractor'),
            get_string('replacement', 'tool_imageextractor'),
        ];
        foreach ($review['rows'] as $prow) {
            $resolved = $replacer->replacement_for($prow->filename);
            $ptable->data[] = [
                s($prow->filename),
                s($prow->component),
                s($prow->filearea),
                display_size((int) $prow->filesize),
                $resolved
                    ? s($resolved->get_filename())
                    : html_writer::tag('em', get_string('replacenomatchcell', 'tool_imageextractor')),
            ];
        }
        echo html_writer::table($ptable);
    }
}

/**
 * Render one thumbnail cell for the replace review preview: a small, capped
 * image when a URL is given, or a muted placeholder when there is nothing to
 * show (a non-image target, or an item with no matching replacement).
 *
 * @param moodle_url|null $url The image URL, or null for a placeholder.
 * @param string $alt Alt text for the image.
 * @return string HTML.
 */
function tool_imageextractor_thumbnail(?moodle_url $url, string $alt): string {
    if ($url === null) {
        return html_writer::div(
            get_string('nothumbnail', 'tool_imageextractor'),
            'text-muted small text-center',
            ['style' => 'width: 120px']
        );
    }
    $img = html_writer::empty_tag('img', [
        'src' => $url->out(false),
        'alt' => $alt,
        'loading' => 'lazy',
        'style' => 'max-width: 120px; max-height: 120px; height: auto; width: auto;',
    ]);
    return html_writer::div($img, '', ['style' => 'width: 120px']);
}
