<?php
// Copyright (c) Skin Cancer College Australasia.
// All rights reserved.
//
// This file is part of a proprietary plugin developed by Skin Cancer
// College Australasia for use with Moodle. It is NOT free software and is
// NOT released under the GNU General Public License.
//
// Unauthorised copying, distribution, modification, or use of this file,
// in whole or in part, via any medium, is strictly prohibited without the
// prior written permission of Skin Cancer College Australasia. The software
// is provided "as is", without warranty of any kind, express or implied.

/**
 * Plugin-level callbacks.
 *
 * @package    tool_imageextractor
 * @copyright  © Skin Cancer College Australasia
 * @license    Proprietary — Skin Cancer College Australasia, all rights reserved
 */

/**
 * Serve the ZIP volumes and manifest generated by an extraction job.
 *
 * Only holders of tool/imageextractor:manage at the system context can fetch
 * them - the archives can contain any file in the site.
 *
 * @param stdClass $course
 * @param stdClass $cm
 * @param context $context
 * @param string $filearea
 * @param array $args
 * @param bool $forcedownload
 * @param array $options
 * @return bool False if the file cannot be served; otherwise it is sent and the script exits.
 */
function tool_imageextractor_pluginfile($course, $cm, $context, $filearea, $args, $forcedownload, array $options = []): bool {
    unset($course, $cm);

    if ($context->contextlevel !== CONTEXT_SYSTEM) {
        return false;
    }
    if (!in_array($filearea, ['volumes', 'manifest'], true)) {
        return false;
    }

    require_login();
    require_capability('tool/imageextractor:manage', $context);

    $itemid = (int) array_shift($args);
    $filename = array_pop($args);
    $filepath = $args ? '/' . implode('/', $args) . '/' : '/';

    $fs = get_file_storage();
    $file = $fs->get_file($context->id, 'tool_imageextractor', $filearea, $itemid, $filepath, $filename);
    if (!$file || $file->is_directory()) {
        return false;
    }

    // Always force download for these (potentially very large) archives.
    send_stored_file($file, 0, 0, true, $options);
}
