<?php
// Copyright (c) Skin Cancer College Australasia.
// All rights reserved.
//
// This file is part of a proprietary plugin developed by Skin Cancer
// College Australasia for use with Moodle. It is NOT free software and is
// NOT released under the GNU General Public License.
//
// Unauthorised copying, distribution, modification, or use of this file,
// in whole or in part, via any medium, is strictly prohibited without the
// prior written permission of Skin Cancer College Australasia. The software
// is provided "as is", without warranty of any kind, express or implied.

/**
 * Plugin-level callbacks.
 *
 * @package    tool_imageextractor
 * @copyright  © Skin Cancer College Australasia
 * @license    Proprietary — Skin Cancer College Australasia, all rights reserved
 */

/**
 * Serve the ZIP volumes and manifest generated by an extraction job, and the
 * uploaded replacement images used by a replace job (for the review preview).
 *
 * Only holders of tool/imageextractor:manage at the system context can fetch
 * them - the archives can contain any file in the site.
 *
 * @param stdClass $course
 * @param stdClass $cm
 * @param context $context
 * @param string $filearea
 * @param array $args
 * @param bool $forcedownload
 * @param array $options
 * @return bool False if the file cannot be served; otherwise it is sent and the script exits.
 */
function tool_imageextractor_pluginfile($course, $cm, $context, $filearea, $args, $forcedownload, array $options = []): bool {
    unset($course, $cm);

    if ($context->contextlevel !== CONTEXT_SYSTEM) {
        return false;
    }
    if (!in_array($filearea, ['volumes', 'manifest', 'replacement'], true)) {
        return false;
    }

    require_login();
    require_capability('tool/imageextractor:manage', $context);

    $itemid = (int) array_shift($args);
    $filename = array_pop($args);
    $filepath = $args ? '/' . implode('/', $args) . '/' : '/';

    $fs = get_file_storage();
    $file = $fs->get_file($context->id, 'tool_imageextractor', $filearea, $itemid, $filepath, $filename);
    if (!$file || $file->is_directory()) {
        return false;
    }

    // The replacement images are shown inline as thumbnails on the review page
    // and are cacheable; the (potentially very large) archives are always
    // downloaded.
    if ($filearea === 'replacement') {
        send_stored_file($file, DAYSECS, 0, false, $options);
    } else {
        send_stored_file($file, 0, 0, true, $options);
    }
}

/**
 * Render a small progress bar with a "done / total (pct%)" caption, used on
 * the jobs overview and the job view page.
 *
 * @param int $done Items processed so far.
 * @param int $total Total items the job matched.
 * @param bool $approx Caption the total as an estimate ("done / ~total"), for
 *                     stages whose denominator is a prior estimate rather than
 *                     an exact count (the analysis scan).
 * @return string HTML, or an em dash when there is nothing to report.
 */
function tool_imageextractor_progress_bar(int $done, int $total, bool $approx = false): string {
    if ($total <= 0) {
        return '-';
    }
    $done = min(max($done, 0), $total);
    $pct = (int) round(($done / $total) * 100);

    $bar = html_writer::div(
        html_writer::div('', 'progress-bar', [
            'role' => 'progressbar',
            'style' => 'width: ' . $pct . '%',
            'aria-valuenow' => $pct,
            'aria-valuemin' => 0,
            'aria-valuemax' => 100,
            'aria-label' => get_string('progress', 'tool_imageextractor'),
        ]),
        'progress',
        ['style' => 'min-width: 6em']
    );
    $caption = $done . ' / ' . ($approx ? '~' : '') . $total . ' (' . $pct . '%)';
    return $bar . html_writer::div($caption, 'small text-nowrap');
}

/**
 * Render the live progress of a job's current background stage (clearing
 * previous results, or scanning for matches), or '' when the job is not in a
 * reporting stage. Shown while a job runs so a large analysis is no longer a
 * black box between "queued" and "results ready".
 *
 * @param stdClass $job The job record.
 * @return string HTML, or '' when there is no stage progress to show.
 */
function tool_imageextractor_stage_progress(stdClass $job): string {
    $stage = (string) ($job->progressstage ?? '');
    if (!in_array($stage, ['clear', 'match', 'optimize'], true) || (int) $job->progresstotal <= 0) {
        return '';
    }
    // The denominator is an upfront estimate for the match scan (files can be
    // added or removed while it runs) - caption it as approximate.
    return html_writer::div(get_string('progressstage_' . $stage, 'tool_imageextractor'), 'small fw-bold')
        . tool_imageextractor_progress_bar((int) $job->progressdone, (int) $job->progresstotal, $stage === 'match');
}

/**
 * Render the destructive-replace confirmation preview for a job: a side-by-side
 * thumbnail comparison of the first few matched targets with the replacement
 * that will be written, followed by a sample table naming each resolved
 * replacement (or flagging targets with no match). Replacements are resolved
 * through the same path the apply uses, so the preview links the exact file
 * that will be written.
 *
 * @param stdClass $job The replace job (its replacement source is stored).
 * @param moodle_url $viewurl The job view URL (unused placeholder for symmetry).
 * @return void
 */
function tool_imageextractor_render_replace_preview(stdClass $job, moodle_url $viewurl): void {
    global $OUTPUT;
    unset($viewurl);

    $review = \tool_imageextractor\manager::review_summary((int) $job->id);

    // Alt-text: no thumbnails and no replacement resolution - preview the
    // planned description against the current alt text of a sample of targets.
    if ($job->replacemode === 'alttext') {
        echo $OUTPUT->heading(get_string('altpreviewheading', 'tool_imageextractor'), 3);
        echo html_writer::div(
            get_string('reviewsummarytotalalt', 'tool_imageextractor', $review['total']),
            'mb-2'
        );
        $replacer = new \tool_imageextractor\replacer($job);
        if ($review['rows']) {
            $atable = new html_table();
            $atable->attributes['class'] = 'generaltable';
            $atable->head = [
                get_string('colfilename', 'tool_imageextractor'),
                get_string('component', 'tool_imageextractor'),
                get_string('colcurrentalt', 'tool_imageextractor'),
                get_string('colnewalt', 'tool_imageextractor'),
            ];
            foreach ($review['rows'] as $prow) {
                $reference = \tool_imageextractor\htmllocator::reference($prow);
                $current = [];
                foreach (\tool_imageextractor\htmllocator::locate($prow) as $loc) {
                    foreach (\tool_imageextractor\htmllocator::extract_alts($loc->html, $reference) as $a) {
                        $current[] = $a;
                    }
                }
                $planned = $replacer->planned_alt($prow->filename);
                $atable->data[] = [
                    s($prow->filename),
                    s($prow->component),
                    $current ? s(implode(' | ', array_unique($current)))
                        : html_writer::tag('em', get_string('altnonecell', 'tool_imageextractor')),
                    $planned === null
                        ? html_writer::tag('em', get_string('altnomappingcell', 'tool_imageextractor'))
                        : s($planned),
                ];
            }
            echo html_writer::table($atable);
        }
        return;
    }

    // Metadata-only: no thumbnails and no replacement resolution - preview the
    // planned author/license change against a sample of the current values.
    if ($job->replacemode === 'metadata') {
        echo $OUTPUT->heading(get_string('metadatapreviewheading', 'tool_imageextractor'), 3);
        echo html_writer::div(
            get_string('reviewsummarytotalmetadata', 'tool_imageextractor', $review['total']),
            'mb-2'
        );
        $planned = [];
        if ((string) $job->metaauthor !== '') {
            $planned[] = get_string('metaauthor', 'tool_imageextractor') . ': ' . s($job->metaauthor);
        }
        if ((string) $job->metalicense !== '') {
            $planned[] = get_string('metalicense', 'tool_imageextractor') . ': ' . s($job->metalicense);
        }
        if ($planned) {
            echo html_writer::div(implode(' · ', $planned), 'mb-3 fw-bold');
        }
        if ($review['rows']) {
            $mtable = new html_table();
            $mtable->attributes['class'] = 'generaltable';
            $mtable->head = [
                get_string('colfilename', 'tool_imageextractor'),
                get_string('component', 'tool_imageextractor'),
                get_string('colcurrentauthor', 'tool_imageextractor'),
                get_string('colcurrentlicense', 'tool_imageextractor'),
            ];
            foreach ($review['rows'] as $prow) {
                $mtable->data[] = [
                    s($prow->filename),
                    s($prow->component),
                    s((string) ($prow->author ?? '')),
                    s((string) ($prow->license ?? '')),
                ];
            }
            echo html_writer::table($mtable);
        }
        return;
    }

    echo $OUTPUT->heading(get_string('replacepreviewheading', 'tool_imageextractor'), 3);
    // Report only the total matched, not an exact replace/skip split: the
    // replacement is resolved at apply time, so every matched row still counts
    // as pending here and an exact "all will be replaced" headline would
    // over-state a ZIP that does not cover every filename.
    echo html_writer::div(
        get_string('reviewsummarytotal', 'tool_imageextractor', $review['total']),
        'mb-2'
    );
    // Single mode writes the one image over every target (nothing is skipped),
    // so only ZIP mode needs the "unmatched filenames are skipped" caveat.
    if ($job->replacemode === 'zip') {
        echo $OUTPUT->notification(get_string('replacezipskipnote', 'tool_imageextractor'), 'info');
    }

    $replacer = new \tool_imageextractor\replacer($job);
    $thumbrows = array_slice($review['rows'], 0, 5);
    if ($thumbrows) {
        echo $OUTPUT->heading(get_string('previewthumbsheading', 'tool_imageextractor'), 4);
        $ttable = new html_table();
        $ttable->attributes['class'] = 'generaltable';
        $ttable->head = [
            get_string('colcurrentimage', 'tool_imageextractor'),
            get_string('colreplacementimage', 'tool_imageextractor'),
            get_string('colfilename', 'tool_imageextractor'),
        ];
        foreach ($thumbrows as $prow) {
            $oldurl = null;
            if (strpos((string) $prow->mimetype, 'image/') === 0) {
                $oldurl = moodle_url::make_pluginfile_url(
                    $prow->contextid,
                    $prow->component,
                    $prow->filearea,
                    $prow->fileitemid,
                    $prow->filepath,
                    $prow->filename
                );
            }
            $newurl = null;
            $replacementfile = $replacer->replacement_for($prow->filename);
            if ($replacementfile) {
                $newurl = moodle_url::make_pluginfile_url(
                    $replacementfile->get_contextid(),
                    $replacementfile->get_component(),
                    $replacementfile->get_filearea(),
                    $replacementfile->get_itemid(),
                    $replacementfile->get_filepath(),
                    $replacementfile->get_filename()
                );
            }
            $ttable->data[] = [
                tool_imageextractor_thumbnail($oldurl, get_string('colcurrentimage', 'tool_imageextractor')),
                tool_imageextractor_thumbnail($newurl, get_string('colreplacementimage', 'tool_imageextractor')),
                s($prow->filename),
            ];
        }
        echo html_writer::table($ttable);
    }

    if ($review['rows']) {
        $ptable = new html_table();
        $ptable->attributes['class'] = 'generaltable';
        $ptable->head = [
            get_string('colfilename', 'tool_imageextractor'),
            get_string('component', 'tool_imageextractor'),
            get_string('filearea', 'tool_imageextractor'),
            get_string('colsize', 'tool_imageextractor'),
            get_string('replacement', 'tool_imageextractor'),
        ];
        foreach ($review['rows'] as $prow) {
            $resolved = $replacer->replacement_for($prow->filename);
            $ptable->data[] = [
                s($prow->filename),
                s($prow->component),
                s($prow->filearea),
                display_size((int) $prow->filesize),
                $resolved
                    ? s($resolved->get_filename())
                    : html_writer::tag('em', get_string('replacenomatchcell', 'tool_imageextractor')),
            ];
        }
        echo html_writer::table($ptable);
    }
}

/**
 * Render one thumbnail cell for the replace review preview: a small, capped
 * image when a URL is given, or a muted placeholder when there is nothing to
 * show (a non-image target, or an item with no matching replacement).
 *
 * @param moodle_url|null $url The image URL, or null for a placeholder.
 * @param string $alt Alt text for the image.
 * @return string HTML.
 */
function tool_imageextractor_thumbnail(?moodle_url $url, string $alt): string {
    if ($url === null) {
        return html_writer::div(
            get_string('nothumbnail', 'tool_imageextractor'),
            'text-muted small text-center',
            ['style' => 'width: 120px']
        );
    }
    $img = html_writer::empty_tag('img', [
        'src' => $url->out(false),
        'alt' => $alt,
        'loading' => 'lazy',
        'style' => 'max-width: 120px; max-height: 120px; height: auto; width: auto;',
    ]);
    return html_writer::div($img, '', ['style' => 'width: 120px']);
}

/**
 * Build a human-readable summary of the search criteria a job was defined with,
 * for the job view page: how files are selected, the course/category/activity
 * scope (resolved to names), and every option that was set. Only rows that
 * carry a value are returned, so the table stays concise.
 *
 * @param stdClass $job The job record.
 * @return array List of [label, value] string pairs.
 */
function tool_imageextractor_criteria_rows(stdClass $job): array {
    $criteria = \tool_imageextractor\manager::decode_criteria($job);
    $rows = [];

    // How the files are selected (the criteria fields, or a CSV mode).
    $mode = $job->csvmode !== '' ? $job->csvmode : 'none';
    $rows[] = [
        get_string('csvmode', 'tool_imageextractor'),
        get_string('csvmode_' . $mode, 'tool_imageextractor'),
    ];

    // A match-list CSV nominates exact files and ignores the criteria fields.
    if ($mode === 'match') {
        if (!empty($criteria['filenames']) && is_array($criteria['filenames'])) {
            $rows[] = [get_string('criteriamatchfiles', 'tool_imageextractor'), count($criteria['filenames'])];
        }
        if (!empty($criteria['contenthashes']) && is_array($criteria['contenthashes'])) {
            $rows[] = [get_string('criteriamatchhashes', 'tool_imageextractor'), count($criteria['contenthashes'])];
        }
    } else {
        $rows[] = [
            get_string('imageonly', 'tool_imageextractor'),
            empty($criteria['imageonly']) ? get_string('no') : get_string('yes'),
        ];

        $courses = tool_imageextractor_name_list('course', 'shortname', $criteria['courseids'] ?? []);
        if ($courses !== '') {
            $rows[] = [get_string('courses', 'tool_imageextractor'), $courses];
        }
        $categories = tool_imageextractor_name_list('course_categories', 'name', $criteria['categoryids'] ?? []);
        if ($categories !== '') {
            $rows[] = [get_string('categories', 'tool_imageextractor'), $categories];
        }

        if (!empty($criteria['modname'])) {
            $modname = (string) $criteria['modname'];
            $label = get_string_manager()->string_exists('modulename', 'mod_' . $modname)
                ? get_string('modulename', 'mod_' . $modname) : $modname;
            $rows[] = [get_string('modtype', 'tool_imageextractor'), $label];
        }
        if (!empty($criteria['modinstancepattern'])) {
            $rows[] = [get_string('modinstancepattern', 'tool_imageextractor'), s($criteria['modinstancepattern'])];
        }
        if (!empty($criteria['component'])) {
            $rows[] = [get_string('component', 'tool_imageextractor'), s($criteria['component'])];
        }
        if (!empty($criteria['filearea'])) {
            $rows[] = [get_string('filearea', 'tool_imageextractor'), s($criteria['filearea'])];
        }
        if (!empty($criteria['filenamepattern'])) {
            $rows[] = [get_string('filenamepattern', 'tool_imageextractor'), s($criteria['filenamepattern'])];
        }
        if (!empty($criteria['mimetypes']) && is_array($criteria['mimetypes'])) {
            $rows[] = [get_string('mimetypes', 'tool_imageextractor'), s(implode(', ', $criteria['mimetypes']))];
        }
        if (!empty($criteria['minsize'])) {
            $rows[] = [get_string('minsizekb', 'tool_imageextractor'), display_size((int) $criteria['minsize'])];
        }
        if (!empty($criteria['maxsize'])) {
            $rows[] = [get_string('maxsizekb', 'tool_imageextractor'), display_size((int) $criteria['maxsize'])];
        }
        if (!empty($criteria['datefrom'])) {
            $rows[] = [get_string('datefrom', 'tool_imageextractor'), userdate((int) $criteria['datefrom'])];
        }
        if (!empty($criteria['dateto'])) {
            $rows[] = [get_string('dateto', 'tool_imageextractor'), userdate((int) $criteria['dateto'])];
        }
        if (!empty($criteria['rows']) && is_array($criteria['rows'])) {
            $rows[] = [get_string('criteriarows', 'tool_imageextractor'), count($criteria['rows'])];
        }
    }

    // Refinements apply whichever way files are selected.
    if (!empty($job->missingonly)) {
        $rows[] = [get_string('missingonly', 'tool_imageextractor'), get_string('yes')];
    }
    if (!empty($job->altmissing)) {
        $rows[] = [get_string('altmissing', 'tool_imageextractor'), get_string('yes')];
    }

    return $rows;
}

/**
 * Resolve a list of record ids to a comma-separated list of names, capped so a
 * huge scope does not overflow the page (with a "+N more" tail). Ids with no
 * matching record are shown as "#id".
 *
 * @param string $table The table to read (e.g. 'course').
 * @param string $namefield The column holding the display name.
 * @param mixed $ids An array of ids (anything else yields '').
 * @param int $cap Maximum names to list before summarising the remainder.
 * @return string
 */
function tool_imageextractor_name_list(string $table, string $namefield, $ids, int $cap = 10): string {
    global $DB;
    if (empty($ids) || !is_array($ids)) {
        return '';
    }
    $ids = array_values(array_unique(array_filter(array_map('intval', $ids), fn($id) => $id > 0)));
    if (!$ids) {
        return '';
    }
    $records = $DB->get_records_list($table, 'id', $ids, '', 'id, ' . $namefield);
    $names = [];
    foreach ($ids as $id) {
        $names[] = isset($records[$id]) ? format_string($records[$id]->{$namefield}) : '#' . $id;
    }
    $shown = array_slice($names, 0, $cap);
    $summary = s(implode(', ', $shown));
    if (count($names) > $cap) {
        $summary .= ' ' . get_string('criteriaandmore', 'tool_imageextractor', count($names) - $cap);
    }
    return $summary;
}
